backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_library:
  name: uploadcare
  config:
    publicKey: 8f74f234379859c37133
    imageShrink: '2000x2000'


collections:
  - label: "Piano"
    identifier_field: title
    name: "piano"
    folder: "_posts/piano"
    create: true
    fields:
      - {label: "Address", name: "title", widget: "string"}
      - {label: "Location Desc", name: "location_desc", widget: "string"}
      - {label: "Submitter", name: "submitter", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
