backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "piano"
    label: "Piano"
    folder: "_posts/piano"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Location Desc", name: "location_desc", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Submitter", name: "submitter", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
